name: Latest blog post workflow

on:
  schedule:  # Run workflow automatically
    - cron: "0 0 1 * *"  # Runs on the first day of every month, at midnight
  # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  workflow_dispatch:

jobs:
  update-readme-with-blog-posts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://sgibson91.github.io/blog/index.xml"
